include:
  - project: "gnome/citemplates"
    file: "flatpak/flatpak_ci_initiative.yml"

stages:
  - test

flatpak:
  variables:
    BUNDLE: "mks-test-widget-dev.flatpak"
    MANIFEST_PATH: "org.gnome.libmks.mks.json"
    FLATPAK_MODULE: "mks"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
    APP_ID: "org.gnome.libmks.mks"
  extends: ".flatpak"
